### ISSUE TITLE
build failed at building kernel ,pls HELP,Guys! 

### ISSUE THREAD

**Issue by andersling** [ArrowOS-Devices/android_device_xiaomi_gauguin#2]
I checkout this git by lunch gauguin and start buid , but it failed when start to build kernel:

>   CC      scripts/mod/empty.o
Android (7485623, based on r416183b1) clang version 12.0.7 (https://android.googlesource.com/toolchain/llvm-project c935d99d7cf2016289302412d7
08641d52d2f7ee)
Target: aarch64-unknown-linux-gnu
Thread model: posix
InstalledDir: /mnt/LineageOS/ArrowOS_12.0_R7/prebuilts/clang/host/linux-x86/clang-r416183b1/bin
Found candidate GCC installation: /mnt/LineageOS/ArrowOS_12.0_R7/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/lib/gcc/aarch64-lin
ux-android/4.9.x
Selected GCC installation: /mnt/LineageOS/ArrowOS_12.0_R7/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/lib/gcc/aarch64-linux-andr
oid/4.9.x
Candidate multilib: .;@m64
Selected multilib: .;@m64
 "/mnt/LineageOS/ArrowOS_12.0_R7/prebuilts/clang/host/linux-x86/clang-r416183b1/bin/clang-12" -cc1 -triple aarch64-unknown-linux-gnu -S -disab
le-free -disable-llvm-verifier -discard-value-names -main-file-name empty.c -mrelocation-model static -meabi gnu -mframe-pointer=non-leaf -rel
axed-aliasing -mdisable-tail-calls -fmath-errno -fno-rounding-math -no-integrated-as -mconstructor-aliases -target-cpu generic -target-feature
 +neon -no-implicit-float -target-abi aapcs -fallow-half-arguments-and-returns -fno-split-dwarf-inlining -debug-info-kind=limited -dwarf-versi
on=4 -debugger-tuning=gdb -v -nostdsysteminc -nobuiltininc -resource-dir /mnt/LineageOS/ArrowOS_12.0_R7/prebuilts/clang/host/linux-x86/clang-r
416183b1/lib64/clang/12.0.7 -isystem ../../../../../../prebuilts/clang/host/linux-x86/clang-r416183b1/lib64/clang/12.0.7/include -include ../.
./../../../../kernel/xiaomi/gauguin/include/linux/kconfig.h -include ../../../../../../kernel/xiaomi/gauguin/include/linux/compiler_types.h -I
 ../../../../../../kernel/xiaomi/gauguin/arch/arm64/include -I ./arch/arm64/include/generated -I ../../../../../../kernel/xiaomi/gauguin/inclu
de -I ./include -I ../../../../../../kernel/xiaomi/gauguin/arch/arm64/include/uapi -I ./arch/arm64/include/generated/uapi -I ../../../../../..
/kernel/xiaomi/gauguin/include/uapi -I ./include/generated/uapi -I ../../../../../../kernel/xiaomi/gauguin/scripts/mod -I scripts/mod -D __KER
NEL__ -D KASAN_SHADOW_SCALE_SHIFT=3 -D CONFIG_BROKEN_GAS_INST=1 -D KASAN_SHADOW_SCALE_SHIFT=3 -D "KBUILD_BASENAME=\"empty\"" -D "KBUILD_MODNAM
E=\"empty\"" -I/usr/include -I/usr/include/x86_64-linux-gnu -O2 -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -Werror-implicit-function-dec
laration -Wno-format-security -Wno-misleading-indentation -Wno-bool-operation -Werror=unknown-warning-option -Wno-unsequenced -Wno-asm-operand
-widths -Wno-initializer-overrides -std=gnu89 -fno-dwarf-directory-asm -fdebug-compilation-dir /mnt/LineageOS/ArrowOS_12.0_R7/out/target/produ
ct/gauguin/obj/KERNEL_OBJ -ferror-limit 19 -stack-protector 2 -fno-signed-char -fwchar-type=short -fno-signed-wchar -fgnuc-version=4.2.1 -vect
orize-loops -vectorize-slp -o /mnt/LineageOS/ArrowOS_12.0_R7/out/soong/.temp/empty-415973.s -x c ../../../../../../kernel/xiaomi/gauguin/scrip
ts/mod/empty.c
clang -cc1 version 12.0.7 based upon LLVM 12.0.7git default target x86_64-unknown-linux-gnu
#include "..." search starts here:
#include <...> search starts here:
 ../../../../../../kernel/xiaomi/gauguin/arch/arm64/include
 ./arch/arm64/include/generated
 ../../../../../../kernel/xiaomi/gauguin/include
 ./include
 ../../../../../../kernel/xiaomi/gauguin/arch/arm64/include/uapi
 ./arch/arm64/include/generated/uapi
 ../../../../../../kernel/xiaomi/gauguin/include/uapi
 ./include/generated/uapi
 ../../../../../../kernel/xiaomi/gauguin/scripts/mod
 scripts/mod
 /usr/include
 /usr/include/x86_64-linux-gnu
 ../../../../../../prebuilts/clang/host/linux-x86/clang-r416183b1/lib64/clang/12.0.7/include
End of search list.
 "/mnt/LineageOS/ArrowOS_12.0_R7/out/.path/aarch64-linux-gnu-as" -EL -I ../../../../../../kernel/xiaomi/gauguin/arch/arm64/include -I ./arch/a
rm64/include/generated -I ../../../../../../kernel/xiaomi/gauguin/include -I ./include -I ../../../../../../kernel/xiaomi/gauguin/arch/arm64/i
nclude/uapi -I ./arch/arm64/include/generated/uapi -I ../../../../../../kernel/xiaomi/gauguin/include/uapi -I ./include/generated/uapi -I ../.
./../../../../kernel/xiaomi/gauguin/scripts/mod -I scripts/mod -o scripts/mod/.tmp_empty.o /mnt/LineageOS/ArrowOS_12.0_R7/out/soong/.temp/empt
y-415973.s
"aarch64-linux-gnu-as" is not allowed to be used. See https://android.googlesource.com/platform/build/+/master/Changes.md#PATH_Tools for more 
information.
clang-12: error: assembler command failed with exit code 1 (use -v to see invocation)
make[3]: *** [/mnt/LineageOS/ArrowOS_12.0_R7/kernel/xiaomi/gauguin/scripts/Makefile.build:341: scripts/mod/empty.o] Error 1
make[2]: *** [/mnt/LineageOS/ArrowOS_12.0_R7/kernel/xiaomi/gauguin/scripts/Makefile.build:644: scripts/mod] Error 2
make[1]: *** [/mnt/LineageOS/ArrowOS_12.0_R7/kernel/xiaomi/gauguin/Makefile:1186: scripts] Error 2
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/mnt/LineageOS/ArrowOS_12.0_R7/out/target/product/gauguin/obj/KERNEL_OBJ'
make: *** [Makefile:146: sub-make] Error 2
make: Leaving directory '/mnt/LineageOS/ArrowOS_12.0_R7/kernel/xiaomi/gauguin'
15:16:59 ninja failed with: exit status 1

> 

anyone any ideas? Thanks!!

**Comment by baolong24** [comment]
```
"aarch64-linux-gnu-as" is not allowed to be used. See https://android.googlesource.com/platform/build/+/master/Changes.md#PATH_Tools for more
information.
```

**Comment by andersling** [comment]
> ```
> "aarch64-linux-gnu-as" is not allowed to be used. See https://android.googlesource.com/platform/build/+/master/Changes.md#PATH_Tools for more
> information.
> ```

would you do me a favor to show me how to disable it ,sir! Big big thanks!!!!!
