### ISSUE TITLE
Does not boot to Arrow OS recovery

### ISSUE THREAD

**Issue by shahiljain** [ArrowOS-Devices/android_device_xiaomi_gauguin#3]
Hey I had flashed the Feb 16 build on my Mi10i and when I boot into recovery it starts up the Mi Recovery... I have to manually update the os everytime (updater doesn't work) ... Is there an arrow recovery boot image that I can use? Also is there a way to make it permanent? Thanks.

**Comment by LynnrinChan** [comment]
You can use PE recovery or Lineage Recovery, basically they have same function.

**Comment by shahiljain** [comment]
So do I have to use my laptop everytime I want to update? Is there a reason it's not possible for the recovery to stick after os update?
